WCAG replacing FAST
webmachinelearning/ethical-webmachinelearning pull request #13
Opened 2022-04-23 10:45 UTC by bbcjamesfletcher

@anssiko this change is in response to https://github.com/webmachinelearning/ethical-webmachinelearning/issues/10

I'll outline the rationale in the issue thread, if every is happy can you review this?

2022-04-25 09:43 UTC, anssiko commented
@michael-n-cooper does this PR look good to you? This is in response to the comments in issue #10. Thank you for your review and suggestions.

2022-04-25 14:08 UTC, michael-n-cooper requested changes
publisher for WCAG 2.1 should be "W3C Accessibility Guidelines Working Group", otherwise looks ok

2022-05-03 13:18 UTC, anssiko commented on index.bs
> +    "publisher": "W3C Accessible Platform Architectures Working Group"
```suggestion
    "publisher": "W3C Accessibility Guidelines Working Group"
```

2022-05-03 13:21 UTC, anssiko commented
Thanks @michael-n-cooper for your review. I've addressed your comment as proposed.

2022-05-03 13:22 UTC, anssiko approved these changes

2022-05-03 13:22 UTC, merged